export const GET_SHOPPING_LISTS = 'GET_SHOPPING_LISTS';
export const DELETE_SHOPPING_LIST = 'DELETE_SHOPPING_LIST';
export const CLEAR_SHOPPING_LISTS_FROM_STORE = 'GET_SHOPPING_LISTS';

export const GET_SHOPPING_LIST = 'GET_SHOPPING_LIST';
export const CLEAR_ACTIVE_SHOPPING_LIST_FROM_STORE =
    'GET_ACTIVE_SHOPPING_LIST_FROM_STORE';
