export const GET_SHOPPING_LISTS = 'GET_SHOPPING_LISTS';
export const DELETE_SHOPPING_LIST = 'DELETE_SHOPPING_LIST';
export const CLEAR_SHOPPING_LISTS_FROM_STORE =
    'CLEAR_SHOPPING_LISTS_FROM_STORE';

export const GET_SHOPPING_LIST = 'GET_SHOPPING_LIST';
export const DELETE_SHOPPING_LIST_PRODUCT = 'DELETE_SHOPPING_LIST_PRODUCT';
export const CLEAR_ACTIVE_SHOPPING_LIST_FROM_STORE =
    'CLEAR_ACTIVE_SHOPPING_LIST_FROM_STORE';

export const TOGGLE_SELECTED_LANGUAGE = 'TOGGLE_SELECTED_LANGUAGE';
